apiVersion: cache.sk1.services.com/v1alpha1
kind: DistributedCache
metadata:
  name: orders-cache
  namespace: default
spec:
  replicas: 3
  image: ghcr.io/golfrider/tiny-cache:0.1.0
  memoryPerPod: 128Mi
  drain:
    gracePeriodSeconds: 30