apiVersion: cache.sk1.services.com/v1alpha1
kind: DistributedCache
metadata:
  name: orders-cache
  namespace: default
spec:
  replicas: 3
  image: tiny-cache:dev
  memoryPerPod: 128Mi
  drain:
    gracePeriodSeconds: 30